# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sSsSSh19ilbvpToLLi0M5EFxcRT8ufS1
"""

num1=int(input("enter ur first num"))
num2=int(input("enter ur second num"))
print(num1+num2)
print(num1-num2)
print(num1*num2)
print(num1/num2)
print(num1%num2)