# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqlzfAI5LRZSBA2B_TadrpjwdO0DkEZ5
"""

name= input("enter your name")
print(name)

