# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sSsSSh19ilbvpToLLi0M5EFxcRT8ufS1
"""

num = int(input("Enter a number: "))
print(num*num)