# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# New Section
"""

print("hello world")

name = "Asad"
print(name)

Age = "20"
print(Age)

a=20
b=10
print(a+b)

print("enter the num")

